# Generated by Django 5.2.3 on 2025-06-12 13:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(choices=[('M', 'Homme'), ('F', 'Femme')], max_length=1)),
                ('code_postal', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Aidant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$')])),
                ('lien_parente', models.CharField(max_length=100)),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aidants', to='gestion.beneficiaire')),
            ],
        ),
        migrations.CreateModel(
            name='Experimentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TelegrafiK', 'TelegrafiK'), ('Presage', 'Presage')], max_length=20)),
                ('coordinateur', models.CharField(max_length=100)),
                ('cohorte', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('noninitie', 'Non initié'), ('visite', 'Visite programmée'), ('consentement', 'Consentement signé'), ('consentementTGK', 'Consentement signé (TelegrafiK)'), ('installation', 'Installation programmée'), ('actif', 'Actif'), ('interrompu', 'Interrompu'), ('fini', 'Fini'), ('desinstalle', 'Désinstallé')], max_length=20)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('adresse_domicile', models.TextField(blank=True)),
                ('methode_recrutement', models.CharField(blank=True, choices=[('evenement', 'Événement'), ('partenaire', 'Partenaire'), ('usager', 'Usager pro')], max_length=20)),
                ('detail_recrutement', models.CharField(blank=True, max_length=200)),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experimentations', to='gestion.beneficiaire')),
            ],
        ),
        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('type_fichier', models.CharField(choices=[('formulaire_ri2s', 'Formulaire RI2S'), ('consentement_telegrafik', 'Consentement TELEGRAFIK'), ('bon_installation', "Bon d'installation"), ('consentement_ri2s', 'Consentement RI2S')], max_length=50)),
                ('experimentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='gestion.experimentation')),
            ],
        ),
    ]
