# Generated by Django 5.2.3 on 2025-06-12 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_beneficiaire_created_at_alter_beneficiaire_sexe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidant',
            name='telephone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Le numéro doit contenir exactement 10 chiffres.')]),
        ),
    ]
