# Generated by Django 5.2.3 on 2025-06-13 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_customfield_experimentationcohorte_customfieldoption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newexperimentation',
            name='custom_fields',
        ),
        migrations.RemoveField(
            model_name='customfieldoption',
            name='custom_field',
        ),
        migrations.RemoveField(
            model_name='newexperimentation',
            name='cohorts',
        ),
        migrations.RemoveField(
            model_name='newexperimentation',
            name='beneficiaire',
        ),
        migrations.DeleteModel(
            name='CustomField',
        ),
        migrations.DeleteModel(
            name='CustomFieldOption',
        ),
        migrations.DeleteModel(
            name='ExperimentationCohorte',
        ),
        migrations.DeleteModel(
            name='NewExperimentation',
        ),
    ]
