# Generated by Django 5.2.3 on 2025-06-13 13:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_remove_newexperimentation_custom_fields_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du champ')),
                ('type', models.CharField(choices=[('text', 'Texte'), ('date', 'Date'), ('number', 'Nombre'), ('file', 'Fichier'), ('select', 'Liste déroulante')], max_length=20, verbose_name='Type de champ')),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentationNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'expérimentation")),
                ('entreprise', models.CharField(max_length=200, verbose_name='Entreprise partenaire')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('remarques', models.TextField(blank=True, verbose_name='Remarques')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('contact_nom', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-zÀ-ÿ \\-]{2,}$', message='Le nom doit contenir au moins 2 lettres.')], verbose_name='Nom du contact')),
                ('contact_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message="L'adresse e-mail semble incorrecte.")], verbose_name='Email du contact')),
                ('contact_telephone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Le numéro doit contenir exactement 10 chiffres.')], verbose_name='Téléphone du contact')),
            ],
        ),
        migrations.CreateModel(
            name='CustomFieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=200, verbose_name='Option')),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='gestion.customfield', verbose_name='Champ personnalisé')),
            ],
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, verbose_name='Valeur texte')),
                ('value_date', models.DateField(blank=True, null=True, verbose_name='Valeur date')),
                ('value_number', models.FloatField(blank=True, null=True, verbose_name='Valeur numérique')),
                ('value_file', models.FileField(blank=True, null=True, upload_to='custom_fields/%Y/%m/%d/', verbose_name='Fichier')),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='gestion.customfield', verbose_name='Champ personnalisé')),
            ],
        ),
        migrations.AddField(
            model_name='customfield',
            name='experimentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='gestion.experimentationnew', verbose_name='Expérimentation'),
        ),
        migrations.CreateModel(
            name='Cohorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la cohorte')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('experimentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohortes', to='gestion.experimentationnew', verbose_name='Expérimentation')),
            ],
        ),
    ]
