# Generated by Django 5.2.3 on 2025-06-13 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_customfield_experimentationnew_customfieldoption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactReferent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='experimentation',
        ),
        migrations.RemoveField(
            model_name='customfieldoption',
            name='custom_field',
        ),
        migrations.AlterField(
            model_name='cohorte',
            name='date_debut',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cohorte',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cohorte',
            name='nom',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='ExperimentationGenerale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('entreprise', models.CharField(max_length=255)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('remarques', models.TextField(blank=True)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='experimentation_generale', to='gestion.contactreferent')),
            ],
        ),
        migrations.CreateModel(
            name='ChampPersonnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_champ', models.CharField(max_length=255)),
                ('type_champ', models.CharField(choices=[('text', 'Texte'), ('date', 'Date'), ('number', 'Nombre'), ('file', 'Fichier'), ('select', 'Liste déroulante')], max_length=20)),
                ('valeurs_possibles', models.TextField(blank=True, help_text="Séparer les valeurs par des virgules si 'select'")),
                ('experimentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champs_perso', to='gestion.experimentationgenerale')),
            ],
        ),
        migrations.AlterField(
            model_name='cohorte',
            name='experimentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohortes', to='gestion.experimentationgenerale'),
        ),
        migrations.DeleteModel(
            name='CustomFieldValue',
        ),
        migrations.DeleteModel(
            name='CustomField',
        ),
        migrations.DeleteModel(
            name='CustomFieldOption',
        ),
        migrations.DeleteModel(
            name='ExperimentationNew',
        ),
    ]
