# Generated by Django 5.2.3 on 2025-06-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_contactreferent_remove_customfield_experimentation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsagerPro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('telephone', models.CharField(max_length=10, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email professionnel')),
                ('profession', models.CharField(choices=[('Infirmier', 'Infirmier'), ('Médecin', 'Médecin'), ('Ergothérapeute', 'Ergothérapeute'), ('Autre', 'Autre')], max_length=50, verbose_name='Profession')),
                ('structure', models.CharField(max_length=200, verbose_name='Structure / Établissement')),
                ('remarques', models.TextField(blank=True, verbose_name='Remarques')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Usager professionnel',
                'verbose_name_plural': 'Usagers professionnels',
            },
        ),
    ]
