# Generated by Django 5.2.3 on 2025-06-15 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_experimentation_animal_compagnie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capteurinstallation',
            name='experimentation',
        ),
        migrations.RemoveField(
            model_name='experimentationfile',
            name='experimentation',
        ),
        migrations.RenameField(
            model_name='experimentation',
            old_name='event_time',
            new_name='heure_visite',
        ),
        migrations.RenameField(
            model_name='professionnelsante',
            old_name='etablissement',
            new_name='etablissement_structure',
        ),
        migrations.RemoveField(
            model_name='experimentation',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='experimentation',
            name='otonome_installee',
        ),
        migrations.AddField(
            model_name='experimentation',
            name='application_otono_me',
            field=models.CharField(blank=True, choices=[('oui', 'Oui'), ('non', 'Non')], max_length=3),
        ),
        migrations.AddField(
            model_name='experimentation',
            name='capteurs_disposition',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='experimentation',
            name='capteurs_installer',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='code_postal',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{5}$', message='Le code postal doit contenir exactement 5 chiffres.')]),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='sexe',
            field=models.CharField(choices=[('M', 'Homme'), ('F', 'Femme')], max_length=1),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='telephone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Le numéro doit contenir exactement 10 chiffres.')]),
        ),
        migrations.AlterField(
            model_name='experimentation',
            name='animal_compagnie',
            field=models.CharField(blank=True, choices=[('oui', 'Oui'), ('non', 'Non')], max_length=3),
        ),
        migrations.AlterField(
            model_name='experimentation',
            name='animal_compagnie_detail',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='experimentation',
            name='boite_clefs',
            field=models.CharField(blank=True, choices=[('oui', 'Oui'), ('non', 'Non')], max_length=3),
        ),
        migrations.AlterField(
            model_name='experimentation',
            name='boite_clefs_detail',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='experimentation',
            name='coucher_lever_autonome',
            field=models.CharField(blank=True, choices=[('oui', 'Oui'), ('non', 'Non')], max_length=3),
        ),
        migrations.AlterField(
            model_name='experimentation',
            name='frequence_lever_nuit',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='experimentation',
            name='gir',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='experimentation',
            name='hebergement_personne',
            field=models.CharField(blank=True, choices=[('oui', 'Oui'), ('non', 'Non')], max_length=3),
        ),
        migrations.AlterField(
            model_name='experimentation',
            name='medecin_traitant',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='experimentation',
            name='nombre_pieces_vie',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='experimentation',
            name='prises_proches',
            field=models.CharField(blank=True, choices=[('oui', 'Oui'), ('non', 'Non')], max_length=3),
        ),
        migrations.AlterField(
            model_name='experimentation',
            name='situation',
            field=models.CharField(blank=True, choices=[('couple', 'En couple'), ('seul', 'Seul')], max_length=20),
        ),
        migrations.AlterField(
            model_name='professionnelsante',
            name='telephone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Le numéro doit contenir exactement 10 chiffres.')]),
        ),
        migrations.DeleteModel(
            name='CapteurDisposition',
        ),
        migrations.DeleteModel(
            name='CapteurInstallation',
        ),
        migrations.DeleteModel(
            name='ExperimentationFile',
        ),
    ]
